version: '3'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
        reservations:
          cpus: '0.15'
          memory: 256M
    ports:
      - '3000:3306'
    volumes:
      - .docker/mysql/data:/bitnami/mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=alessandro
      - MARIADB_PASSWORD=alessandro
      - MARIADB_DATABASE=financeiro_pessoal

  codeigniter:
    image: docker.io/bitnami/codeigniter:4.4.4-debian-11-r0
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
    ports:
      - '8000:8000'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - CODEIGNITER_DATABASE_HOST=mariadb
      - CODEIGNITER_DATABASE_PORT_NUMBER=3306
      - CODEIGNITER_DATABASE_USER=alessandro
      - CODEIGNITER_DATABASE_PASSWORD=alessandro
      - CODEIGNITER_DATABASE_NAME=financeiro_pessoal
    volumes:
      - './www:/app'
    depends_on:
      - mariadb